use crate::domain::RuntimeCapabilities;
use crate::domain::{HookResult, HooksDef};
use crate::service::env_apply;
use crate::service::storage_service;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

/// Thin wrapper around platform-specific env handling and hook execution.
pub fn apply_var_persistent(key: &str, value: &str) -> Result<(), String> {
    env_apply::apply_var_persistent(key, value)
}

/// Persists a shell snapshot when the current platform supports it.
pub fn persist_shell_env_snapshot(items: &[(String, String)]) -> Result<Option<String>, String> {
    env_apply::persist_shell_env_snapshot(items)
}

/// Returns the platform capability summary shown in the frontend.
pub fn runtime_capabilities() -> RuntimeCapabilities {
    env_apply::runtime_capabilities()
}

/// Reads a single variable from the persistent scope.
pub fn read_persistent_var(key: &str) -> Result<Option<String>, String> {
    env_apply::read_persistent_var(key)
}

/// Notifies the host OS that environment values changed.
pub fn notify_environment_change() -> Result<(), String> {
    env_apply::notify_environment_change()
}

/// Persists a cross-platform application-level dotenv snapshot for IDEs such as IntelliJ IDEA.
pub fn persist_idea_env_snapshot(items: &[(String, String)]) -> Result<Option<String>, String> {
    let path = idea_env_file_path()?;
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).map_err(|e| {
            format!(
                "failed to create IDEA env directory {}: {}",
                parent.display(),
                e
            )
        })?;
    }

    let content = build_idea_env_content(items)?;
    if let Ok(existing) = fs::read_to_string(&path) {
        if existing == content {
            return Ok(None);
        }
    }

    write_atomic(&path, &content)?;
    Ok(Some(path.display().to_string()))
}

/// Runs post-apply hooks in a shell appropriate for the host OS.
pub fn run_post_hooks(hooks: Option<&HooksDef>) -> Vec<HookResult> {
    let mut results = Vec::new();
    let Some(post_hooks) = hooks.and_then(|h| h.post.as_ref()) else {
        return results;
    };

    for cmd in post_hooks {
        #[cfg(target_os = "windows")]
        let output = Command::new("cmd").args(["/C", cmd]).output();

        #[cfg(not(target_os = "windows"))]
        let output = Command::new("sh").args(["-c", cmd]).output();

        match output {
            Ok(out) => {
                let success = out.status.success();
                let mut msg = String::new();
                if !out.stdout.is_empty() {
                    msg.push_str(&String::from_utf8_lossy(&out.stdout));
                }
                if !out.stderr.is_empty() {
                    if !msg.is_empty() {
                        msg.push_str("\n");
                    }
                    msg.push_str(&String::from_utf8_lossy(&out.stderr));
                }
                results.push(HookResult {
                    command: cmd.clone(),
                    success,
                    code: out.status.code(),
                    message: msg.trim().to_string(),
                });
            }
            Err(e) => results.push(HookResult {
                command: cmd.clone(),
                success: false,
                code: None,
                message: e.to_string(),
            }),
        }
    }
    results
}

fn idea_env_file_path() -> Result<PathBuf, String> {
    let db_path = storage_service::db_path()?;
    let base = db_path
        .parent()
        .ok_or_else(|| "failed to resolve clicky data directory".to_string())?;
    Ok(base.join("env").join("idea").join("current.env"))
}

fn escape_dotenv_value(value: &str) -> String {
    if value.is_empty() {
        return String::new();
    }

    let needs_quotes = value
        .chars()
        .any(|ch| ch.is_whitespace() || matches!(ch, '#' | '"' | '\\'));
    if !needs_quotes {
        return value.to_string();
    }

    let escaped = value.replace('\\', "\\\\").replace('"', "\\\"");
    format!("\"{}\"", escaped)
}

fn build_idea_env_content(items: &[(String, String)]) -> Result<String, String> {
    let mut lines = Vec::with_capacity(items.len() + 4);
    lines.push("# Generated by Clicky".to_string());
    lines.push(
        "# IntelliJ IDEA Run/Debug Configuration can point Environment variables to this file"
            .to_string(),
    );
    lines.push(format!(
        "# Source: {}",
        storage_service::db_path()?.display()
    ));
    lines.push(String::new());

    for (key, value) in items {
        lines.push(format!("{}={}", key, escape_dotenv_value(value)));
    }

    Ok(lines.join("\n") + "\n")
}

fn write_atomic(path: &Path, content: &str) -> Result<(), String> {
    let tmp_path = path.with_extension("tmp");
    fs::write(&tmp_path, content).map_err(|e| {
        format!(
            "failed to write temp env file {}: {}",
            tmp_path.display(),
            e
        )
    })?;
    fs::rename(&tmp_path, path).or_else(|rename_err| {
        if path.exists() {
            fs::remove_file(path).map_err(|e| {
                format!(
                    "failed to remove existing env file {} before replace: {}",
                    path.display(),
                    e
                )
            })?;
            fs::rename(&tmp_path, path)
                .map_err(|e| format!("failed to replace env file {}: {}", path.display(), e))
        } else {
            Err(format!(
                "failed to move temp env file {} to {}: {}",
                tmp_path.display(),
                path.display(),
                rename_err
            ))
        }
    })?;
    Ok(())
}
