environments:
  dev:
    description: Local DEV defaults
    variables:
      ZNDER_MYSQL_HOST: "192.168.60.176"
      ZNDER_MYSQL_PORT: "3306"
      ZNDER_MYSQL_DB: "zender-erp-dev"
      ZNDER_MYSQL_USER: "root"
      ZNDER_MYSQL_PASS: "zender"
    hooks:
      post:
        - "echo Clicky switched to dev"

  sit:
    description: SIT connection values
    variables:
      ZNDER_MYSQL_HOST: "120.76.142.193"
      ZNDER_MYSQL_PORT: "13306"
      ZNDER_MYSQL_DB: "zender_erp_sit"
      ZNDER_MYSQL_USER: "zender_dev"
      ZNDER_MYSQL_PASS: "zender@dev"
    hooks:
      post:
        - "echo Clicky switched to sit"
